const dummyTasks = [
  {
    _id: "1",
    title: "Clean Room",
    estimatedDuration: 5,
    deadline: "10:50",
    hotelApartment: "Room 101 - Grand Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Deep clean bathroom, change sheets, vacuum floor.",
  },
  {
    _id: "100",
    title: "Clean Room 107",
    estimatedDuration: 0.5,
    deadline: "8:00",
    hotelApartment: "Room 101 - Grand Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Deep clean bathroom, change sheets, vacuum floor.",
  },
  {
    _id: "2",
    title: "Vacuum Lobby",
    estimatedDuration: 30,
    deadline: "10:30",
    hotelApartment: "Lobby - Grand Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Vacuum lobby carpet and entrance mats thoroughly.",
  },
  {
    _id: "3",
    title: "Clean Room 205",
    estimatedDuration: 50,
    deadline: "11:30",
    hotelApartment: "Room 205 - City Center Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Full room cleaning including bathroom and dusting.",
  },
  {
    _id: "4",
    title: "Restock Minibar",
    estimatedDuration: 15,
    deadline: "11:45",
    hotelApartment: "Room 302 - Beach Resort",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Refill minibar with drinks, snacks, and check expiry.",
  },
  {
    _id: "5",
    title: "Clean Bathroom Suite 401",
    estimatedDuration: 35,
    deadline: "12:30",
    hotelApartment: "Suite 401 - Grand Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Focus on shower area and marble surfaces.",
  },
  {
    _id: "6",
    title: "Change Bedsheets Room 150",
    estimatedDuration: 20,
    deadline: "12:45",
    hotelApartment: "Room 150 - City Center Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Replace all linens and pillow covers.",
  },
  {
    _id: "7",
    title: "Deep Clean Kitchen",
    estimatedDuration: 90,
    deadline: "14:30",
    hotelApartment: "Kitchen - Beach Resort",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Sanitize surfaces, mop floor, and clean appliances.",
  },
  {
    _id: "8",
    title: "Organize Storage Room",
    estimatedDuration: 40,
    deadline: "15:15",
    hotelApartment: "Storage - Grand Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Sort and label supplies, clean shelves.",
  },
  {
    _id: "9",
    title: "Clean Pool Area",
    estimatedDuration: 60,
    deadline: "16:15",
    hotelApartment: "Pool - Beach Resort",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Wipe down chairs, remove debris, mop tiles.",
  },
  {
    _id: "10",
    title: "Restock Laundry Room",
    estimatedDuration: 25,
    deadline: "16:45",
    hotelApartment: "Laundry - City Center Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Check detergents, refill laundry baskets and stock.",
  },
  {
    _id: "11",
    title: "Clean Conference Room",
    estimatedDuration: 50,
    deadline: "17:45",
    hotelApartment: "Conference Room - Grand Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Clean tables, chairs, whiteboard, and vacuum carpet.",
  },
  {
    _id: "12",
    title: "Replace Towels",
    estimatedDuration: 20,
    deadline: "18:00",
    hotelApartment: "Room 220 - Beach Resort",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Replace bath and hand towels with fresh ones.",
  },
  {
    _id: "13",
    title: "Clean Hallways",
    estimatedDuration: 35,
    deadline: "18:45",
    hotelApartment: "Hallways - Grand Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Sweep and mop all hallway floors, clean walls.",
  },
  {
    _id: "14",
    title: "Refill Soap Dispensers",
    estimatedDuration: 15,
    deadline: "19:00",
    hotelApartment: "All Floors - City Center Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Check and refill all public restroom dispensers.",
  },
  {
    _id: "15",
    title: "Check Fire Extinguishers",
    estimatedDuration: 45,
    deadline: "20:00",
    hotelApartment: "All Buildings - Beach Resort",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Inspect tags and pressure gauges on all units.",
  },
  {
    _id: "16",
    title: "Polish Furniture",
    estimatedDuration: 40,

    deadline: "21:00",
    hotelApartment: "Lobby - City Center Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Polish tables, counters, and wooden frames.",
  },
  {
    _id: "17",
    title: "Clean Windows",
    estimatedDuration: 60,

    deadline: "22:15",
    hotelApartment: "Exterior - Grand Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Use window cleaner for all glass surfaces.",
  },
  {
    _id: "18",
    title: "Inspect Lighting Fixtures",
    estimatedDuration: 30,

    deadline: "22:45",
    hotelApartment: "All Rooms - Beach Resort",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Check bulb conditions and replace any dim lights.",
  },
  {
    _id: "19",
    title: "Organize Supply Closet",
    estimatedDuration: 35,

    deadline: "23:30",
    hotelApartment: "Storage - City Center Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Label shelves, throw out empty containers.",
  },
  {
    _id: "20",
    title: "Test case for overdue",
    estimatedDuration: 0.025,
    deadline: "00:00",
    hotelApartment: "Elevators - Grand Hotel",
    assignedTo: "Maria Rodriguez",
    status: "notStarted",
    details: "Wipe buttons, sanitize rails, clean floor.",
  },
];

export default dummyTasks;
